// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefTool } from "./BriefTool";

/**
 * The five-line check (SRS F3), as the resourcer edits it.
 */
export type BriefLines = { 
/**
 * 1. Seniority titles to search, e.g. "Senior", "Lead", "Principal".
 */
levels: Array<string>, 
/**
 * Titles never searched, e.g. "Director", "VP".
 */
excluded_titles: Array<string>, 
/**
 * 2. Up to three, most important first.
 */
must_haves: Array<string>, 
/**
 * 3. Every tool the spec names.
 */
tools: Array<BriefTool>, 
/**
 * 4. Cities, and whether remote counts.
 */
locations: Array<string>, remote: boolean, 
/**
 * 5. Kinds of employer to search, and companies to leave out.
 */
employer_types: Array<string>, leave_out: Array<string>, };
