// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainWeight } from "./DomainWeight";

/**
 * An area of the business the person should know, e.g. "Digital asset custody".
 */
export type BriefDomain = { name: string, weight: DomainWeight, };
