// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefLines } from "./BriefLines";

export type Brief = { id: string, version: number, lines: BriefLines, drafted_by_ai: boolean, confirmed: boolean, };
