// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefDomain } from "./BriefDomain";
import type { BriefTool } from "./BriefTool";

/**
 * The brief check (SRS F3), as the resourcer edits it. Lines added later
 * default to empty, so a page loaded before an update can still save.
 */
export type BriefLines = { 
/**
 * Claude's short read of the spec: what the search has to find and why.
 * Shown above the brief; never searched.
 */
analysis: string, 
/**
 * Line 1: job titles to search, the spec's own and close variants, e.g.
 * "Cloud Security Engineer". A person's title must contain one.
 */
titles: Array<string>, 
/**
 * Seniority words, e.g. "Senior", "Lead", "Principal". The title must
 * also contain one.
 */
levels: Array<string>, 
/**
 * Titles never searched, e.g. "Director", "VP".
 */
excluded_titles: Array<string>, 
/**
 * Fewest years of work experience, if the spec says. Narrows the search.
 */
min_years: number | null, 
/**
 * 2. Up to three, most important first.
 */
must_haves: Array<string>, 
/**
 * 3. Functional and soft skills. Used to rank and explain, never to filter.
 */
capabilities: Array<string>, 
/**
 * 4. Areas of the business the person should know.
 */
domains: Array<BriefDomain>, 
/**
 * 5. Every tool the spec names.
 */
tools: Array<BriefTool>, 
/**
 * Line 6: standards and regulations, e.g. "NIST CSF", "DORA". Rank
 * only, as few profiles list them.
 */
frameworks: Array<string>, 
/**
 * Certifications the spec asks for, e.g. "CISSP". Rank only.
 */
certifications: Array<string>, 
/**
 * 7. Cities, and whether remote counts.
 */
locations: Array<string>, remote: boolean, 
/**
 * 8. Kinds of employer to search, and companies to leave out.
 */
employer_types: Array<string>, leave_out: Array<string>, };
