// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidacyState } from "./CandidacyState";
import type { ContactLine } from "./ContactLine";
import type { RankCheck } from "./RankCheck";
import type { ReasonCode } from "./ReasonCode";

export type CandidateRow = { 
/**
 * The candidacy (this person for this role).
 */
id: string, 
/**
 * Sent back with a decision, so two people cannot overwrite each other.
 */
version: number, state: CandidacyState, name: string, title: string | null, employer: string | null, location: string | null, 
/**
 * Without the scheme, e.g. "linkedin.com/in/someone".
 */
linkedin_url: string | null, 
/**
 * "A", "B" or "C" once ranked.
 */
tier: string | null, score: number | null, 
/**
 * Why, in one or two sentences. Strong evidence is wrapped in **double asterisks**.
 */
reason: string | null, 
/**
 * Things to check that the profile does not show.
 */
unknowns: Array<string>, 
/**
 * Claude's verdict on each must-have, title, level, years, required tool
 * and Must domain, in the brief's order. Empty when not ranked.
 */
checks: Array<RankCheck>, 
/**
 * Known to the team through another role or a past message.
 */
known: string | null, 
/**
 * Opted out or asked to be erased: never contacted.
 */
do_not_contact: boolean, 
/**
 * No current employer on record: check before any contact.
 */
employer_unknown: boolean, 
/**
 * The wider search that found them, or `None` for the brief's own.
 */
found_by: string | null, has_work_email: boolean, has_phone: boolean, 
/**
 * Work email, personal emails and phones, work first. Empty for anyone
 * who must not be contacted.
 */
contacts: Array<ContactLine>, 
/**
 * The latest CV assessment for this role, out of 10.
 */
cv_score: number | null, 
/**
 * The score is against an older brief; a re-rank is due.
 */
stale_rank: boolean, reject_reason: ReasonCode | null, 
/**
 * What Recruitly knows about them, in words. `None` when not checked or not there.
 */
recruitly_note: string | null, 
/**
 * The Recruitly user who owns their record, to compare with `Me`.
 */
recruitly_owner_id: string | null, recruitly_checked: boolean, 
/**
 * The last check could not reach Recruitly.
 */
recruitly_check_failed: boolean, 
/**
 * Seconds since 1970 of the last check, for "checked 2 hours ago".
 */
recruitly_checked_at: number | null, 
/**
 * When they were sent to Recruitly, e.g. "30 Sep 2026".
 */
sent_to_recruitly: string | null, 
/**
 * Sent into the linked job's pipeline, not only as a candidate.
 */
in_recruitly_pipeline: boolean, 
/**
 * Where their emails are: "draft", "approved", "active", "stopped" or
 * "done", or "reply", "auto" or "bounce" once one arrived. None if never drafted.
 */
email_status: string | null, };
