// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a candidate is for one role. Mirrors the state flow in the design doc.
 */
export type CandidacyState = "found" | "known_checked" | "ranked" | "shortlisted" | "rejected" | "drafted" | "approved" | "contacted" | "replied" | "no_reply" | "handed_to_ats";
