// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateRow } from "./CandidateRow";
import type { CandidateTab } from "./CandidateTab";
import type { RecruitlyLink } from "./RecruitlyLink";

/**
 * The Candidates screen for one role (SRS F6, F7, F9).
 */
export type CandidatesView = { tab: CandidateTab, 
/**
 * The confirmed brief people are ranked against, if there is one.
 */
brief_version: number | null, to_review: number, shortlisted: number, rejected: number, 
/**
 * Found but not ranked yet.
 */
unranked: number, 
/**
 * A ranking is queued or running.
 */
ranking: boolean, 
/**
 * Why ranking cannot run now, in words for people.
 */
rank_blocked: string | null, 
/**
 * Best first. At most `MAX_LISTED` people.
 */
people: Array<CandidateRow>, 
/**
 * Recruitly is set up: shortlisted people are checked there and can be sent over.
 */
recruitly: boolean, 
/**
 * Where people sent to Recruitly land, if the role is linked to a job.
 */
recruitly_job: RecruitlyLink | null, };