// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidacyState } from "./CandidacyState";
import type { ReasonCode } from "./ReasonCode";

export type CandidateRow = { 
/**
 * The candidacy (this person for this role).
 */
id: string, 
/**
 * Sent back with a decision, so two people cannot overwrite each other.
 */
version: number, state: CandidacyState, name: string, title: string | null, employer: string | null, location: string | null, 
/**
 * Without the scheme, e.g. "linkedin.com/in/someone".
 */
linkedin_url: string | null, 
/**
 * "A", "B" or "C" once ranked.
 */
tier: string | null, score: number | null, 
/**
 * Why, in one or two sentences. Strong evidence is wrapped in **double asterisks**.
 */
reason: string | null, 
/**
 * Things to check that the profile does not show.
 */
unknowns: Array<string>, 
/**
 * Known to the team through another role or a past message.
 */
known: string | null, 
/**
 * Opted out or asked to be erased: never contacted.
 */
do_not_contact: boolean, 
/**
 * No current employer on record: check before any contact.
 */
employer_unknown: boolean, has_work_email: boolean, has_phone: boolean, reject_reason: ReasonCode | null, };
