// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three lists on the Candidates screen.
 */
export type CandidateTab = "review" | "shortlisted" | "rejected";
