// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outreach channel. Email is automated; the others are assisted.
 */
export type Channel = "email" | "linkedin" | "whatsapp";
