// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How well the work evidence shows one line of the brief.
 */
export type CheckVerdict = "met" | "partly" | "not_shown";
