// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientUpdate = { name: string, 
/**
 * The client's web domain, e.g. "example.com". Used to keep their staff out.
 */
domain: string, 
/**
 * Never approach their staff for any role.
 */
off_limits: boolean, };
