// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Client = { id: string, name: string, domain: string | null, 
/**
 * Never approach their staff for any role.
 */
off_limits: boolean, };
