// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /api/roles/:id/close
 */
export type CloseRole = { 
/**
 * True to close, false to reopen.
 */
closed: boolean, };
