// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefLines } from "./BriefLines";

/**
 * Confirm exactly these lines. `based_on` is the version the editor loaded
 * (`None` if there was no brief), so a stale window cannot overwrite newer work.
 */
export type ConfirmBrief = { lines: BriefLines, based_on: number | null, };
