// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactKind } from "./ContactKind";

/**
 * One way to reach a person, as the card shows it.
 */
export type ContactLine = { kind: ContactKind, value: string, };
