// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Controls = { 
/**
 * No email goes out while this is on.
 */
sending_paused: boolean, 
/**
 * No paid call (search, ranking, CV assessment) is made while this is on.
 */
paid_calls_paused: boolean, };
