// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Only the switches being changed, so two admins never undo each other.
 */
export type ControlsChange = { sending_paused?: boolean, paid_calls_paused?: boolean, first_emails_per_day?: number, };
