// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountRequest = { 
/**
 * Made fresh by the browser for each press, so a repeat never pays twice.
 */
key: string, };
