// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountLocation } from "./CountLocation";

export type CountView = { id: string, brief_version: number, 
/**
 * Seconds since 1970, for "counted 2 minutes ago".
 */
counted_at: number, 
/**
 * The brief has been confirmed again since, so this count is out of date.
 */
stale: boolean, locations: Array<CountLocation>, credits_used: number, };
