// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CvFeedback } from "./CvFeedback";

export type CvAssessment = { id: string, role_id: string, role_title: string, 
/**
 * The role this card is for.
 */
this_role: boolean, 
/**
 * 1 to 10.
 */
score: number, 
/**
 * The role as Claude names the fit, e.g. "Senior Cloud Security Engineer".
 */
fit_title: string, matches: Array<string>, 
/**
 * Where the CV falls short of the role.
 */
gaps: Array<string>, 
/**
 * Things to treat with caution.
 */
flags: Array<string>, 
/**
 * To ask on the call, most important first.
 */
questions: Array<string>, 
/**
 * The profile rank (0 to 100) for this role, for comparison.
 */
profile_score: number | null, feedback: CvFeedback | null, };
