// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackVerdict } from "./FeedbackVerdict";

export type CvFeedback = { verdict: FeedbackVerdict, 
/**
 * The resourcer's own score, when it differs.
 */
your_score: number | null, note: string, 
/**
 * Positions (from 0) of the questions marked vital.
 */
vital: Array<number>, by: string | null, at: number, };
