// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CvAssessment } from "./CvAssessment";

export type CvInfo = { id: string, file_name: string, 
/**
 * Seconds since 1970.
 */
uploaded_at: number, uploaded_by: string | null, 
/**
 * Claude's overall call across the roles: what to do next.
 */
call: string, 
/**
 * When it was added to Recruitly as a note, e.g. "1 Oct 2026".
 */
recruitly_noted: string | null, 
/**
 * This role first, then the others.
 */
assessments: Array<CvAssessment>, };
