// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CvInfo } from "./CvInfo";
import type { RoleChoice } from "./RoleChoice";

/**
 * The CV panel on a candidate card.
 */
export type CvView = { 
/**
 * The latest CV and its assessments, if one was uploaded.
 */
cv: CvInfo | null, 
/**
 * Other open roles it could also be assessed against.
 */
roles: Array<RoleChoice>, 
/**
 * Recruitly is set up, so the assessment can be added there as a note.
 */
recruitly: boolean, 
/**
 * The person has a Recruitly record to add the note to.
 */
in_recruitly: boolean, };
