// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionAction } from "./DecisionAction";
import type { ReasonCode } from "./ReasonCode";

export type Decision = { action: DecisionAction, 
/**
 * Required to reject.
 */
reason: ReasonCode | null, 
/**
 * The version the screen showed.
 */
version: number, };
