// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DncReason } from "./DncReason";

export type DncEntry = { 
/**
 * A lower-case email, a LinkedIn address or a phone number.
 */
identifier: string, reason: DncReason, 
/**
 * e.g. "2 Oct 2026".
 */
added: string, };
