// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DncEntry } from "./DncEntry";

export type DncList = { entries: Array<DncEntry>, total: number, };
