// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much a domain counts. `Must` narrows the search; `Plus` only lifts
 * the ranking.
 */
export type DomainWeight = "must" | "plus";
