// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackVerdict } from "./FeedbackVerdict";

/**
 * Feedback on one assessment. Saving again replaces it.
 */
export type FeedbackRequest = { verdict: FeedbackVerdict, your_score: number | null, note: string, vital: Array<number>, };
