// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Add a shortlisted person to Recruitly. `confirmed` holds the keys of the
 * questions the resourcer has said yes to (see `HandoverResult`).
 */
export type Handover = { confirmed: Array<string>, };
