// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateRow } from "./CandidateRow";

export type HandoverResult = { 
/**
 * Set when done.
 */
candidate: CandidateRow | null, 
/**
 * Set instead when the resourcer must say yes first, e.g. a colleague
 * owns them in Recruitly. Send `confirm_key` back in `confirmed`.
 */
confirm: string | null, confirm_key: string | null, };