// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Save a role started from a Recruitly job, after the resourcer checked the form.
 */
export type ImportRole = { job_id: string, client_id: string, title: string, spec_text: string, };
