// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Recruitly job read into the new-role form. Nothing is saved yet.
 */
export type JobPreview = { id: string, label: string, title: string, 
/**
 * The description as plain text, with location and pay added.
 */
spec_text: string, company_name: string | null, company_domain: string | null, 
/**
 * The Sourcer client that matches the Recruitly company, if any.
 */
client_id: string | null, 
/**
 * The Sourcer role already made from this job.
 */
role_id: string | null, };