// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Link a role to a Recruitly job, or unlink it with `None`.
 */
export type LinkJob = { job_id: string | null, };
