// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LockedOut = { id: string, name: string, 
/**
 * The client this role is for, rather than an off-limits client.
 */
hiring: boolean, };
