// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MailStatus = { 
/**
 * The server has what it needs to send (sign-in and MAIL_TOKEN_KEY).
 */
configured: boolean, connected: boolean, 
/**
 * The connected mailbox.
 */
address: string | null, 
/**
 * Why sending from it stopped, in words.
 */
broken: string | null, 
/**
 * First emails sent today (Dubai) from this mailbox, and the daily limit.
 */
first_emails_today: number, first_emails_per_day: number, 
/**
 * Where Microsoft must send people back, for the Entra setup steps.
 */
redirect_uri: string, };
