// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signed-in user, as the web app sees them.
 */
export type Me = { id: string, name: string, email: string, 
/**
 * "admin" or "resourcer".
 */
role: string, };
