// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Switch a team member off or back on.
 */
export type MemberUpdate = { disabled: boolean, };
