// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a team member is: invited but never signed in, active, or switched off.
 */
export type MemberStatus = "invited" | "active" | "disabled";
