// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountLocation } from "./CountLocation";

export type MoreCount = { id: string, 
/**
 * Seconds since 1970.
 */
counted_at: number, 
/**
 * The search changed since this count.
 */
stale: boolean, 
/**
 * People not already found for this role, per place.
 */
locations: Array<CountLocation>, credits_used: number, pulled: boolean, };
