// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorePick } from "./MorePick";

/**
 * POST /api/roles/:id/searches/pull
 */
export type MorePullRequest = { picks: Array<MorePick>, 
/**
 * Required when pulling more than 50 people at once.
 */
confirmed: boolean, key: string, };
