// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MorePick = { slot: number, count_id: string, 
/**
 * People to pull from this search, spread over its places.
 */
size: number, };
