// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoreCount } from "./MoreCount";
import type { Widen } from "./Widen";

/**
 * One of a role's wider searches, as the Search screen shows it.
 */
export type MoreSearch = { 
/**
 * 1 and 2 are Claude's picks; 3 is the resourcer's own.
 */
slot: number, by_claude: boolean, name: string, 
/**
 * What it adds and why, in one sentence.
 */
note: string, widen: Widen, version: number, 
/**
 * The places it counts and pulls: only those where it differs from the brief.
 */
locations: Array<string>, 
/**
 * The latest count of this search, if any.
 */
count: MoreCount | null, };
