// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewClient = { name: string, 
/**
 * The client's web domain, e.g. "example.com". Used to keep their staff out.
 */
domain: string, off_limits: boolean, };
