// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DncReason } from "./DncReason";

export type NewDnc = { 
/**
 * An email, a LinkedIn address or a phone number, as typed.
 */
identifier: string, reason: DncReason, };
