// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * An admin invites someone by their Microsoft 365 email address.
 */
export type NewMember = { name: string, email: string, role: Role, };
