// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutreachStepView = { step: number, 
/**
 * Days after the previous email.
 */
delay_days: number, subject: string, body: string, 
/**
 * How it will look, signature and source line included.
 */
html: string, sent_at: string | null, };
