// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a team member signs and introduces themselves.
 */
export type OutreachSettings = { 
/**
 * Plain text. Links as [LinkedIn](https://...) or a bare https:// address.
 */
signature: string, 
/**
 * e.g. "I'm a Director at Austin Werner, a recruitment business".
 */
intro: string, };
