// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutreachStatus } from "./OutreachStatus";
import type { OutreachStepView } from "./OutreachStepView";

export type OutreachView = { 
/**
 * `None` until drafted.
 */
status: OutreachStatus | null, 
/**
 * The personal email it goes to.
 */
to_email: string | null, sender: string, steps: Array<OutreachStepView>, 
/**
 * What stops approval, in words.
 */
problems: Array<string>, 
/**
 * Worth a look, but does not stop approval.
 */
notes: Array<string>, stop_reason: string | null, 
/**
 * e.g. "1 Oct 2026".
 */
approved_at: string | null, 
/**
 * Sent back with changes, so two windows cannot overwrite each other.
 */
version: number, 
/**
 * The Outlook connection is set up, so approved emails will go out.
 */
sending_ready: boolean, };
