// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutreachStepEdit } from "./OutreachStepEdit";

export type OutreachEdit = { version: number, steps: Array<OutreachStepEdit>, };
