// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PullView = { id: string, 
/**
 * The count this pull came from. Each count is pulled from once.
 */
count_id: string, requested: number, pulled: number, new_candidates: number, 
/**
 * Found again: already a candidate for this role.
 */
already: number, 
/**
 * Removed after pulling: current job matched a locked-out company.
 */
left_out: number, unknown_employer: number, credits_used: number, locations: number, locations_done: number, done: boolean, 
/**
 * A location could not be pulled after several tries.
 */
failed: boolean, };
