// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PullView = { id: string, 
/**
 * The count this pull came from. Each count is pulled from once.
 */
count_id: string, requested: number, pulled: number, new_candidates: number, 
/**
 * Found again: already a candidate for this role.
 */
already: number, 
/**
 * Removed after pulling: current job matched a locked-out company.
 */
left_out: number, unknown_employer: number, credits_used: number, locations: number, locations_done: number, done: boolean, 
/**
 * A location could not be pulled after several tries.
 */
failed: boolean, 
/**
 * Which locations failed, by name.
 */
failed_locations: Array<string>, 
/**
 * Credits paid for people who were never saved (a location failed after
 * the provider charged). Already counted in credits_used.
 */
credits_unsaved: number, 
/**
 * The wider search this pull came from, or `None` for the brief.
 */
search_name: string | null, };
