// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullPick } from "./PullPick";

export type PullRequest = { count_id: string, picks: Array<PullPick>, 
/**
 * Required when pulling more than 50 people at once.
 */
confirmed: boolean, key: string, };
