// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckVerdict } from "./CheckVerdict";

/**
 * One line of the brief and Claude's verdict on it for one person.
 */
export type RankCheck = { item: string, verdict: CheckVerdict, };
