// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecruitlyLink = { id: string, 
/**
 * e.g. "Senior IAM Engineer (J-1042)".
 */
label: string, };