// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecruitlyTest = { 
/**
 * The Recruitly user the key belongs to.
 */
connected_as: string, };