// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recruitly for the screens. The key itself never leaves the server.
 */
export type RecruitlyStatus = { configured: boolean, calls_today: number, daily_cap: number, };
