// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A job in Recruitly, to start a role from.
 */
export type RecruitlyJob = { id: string, title: string, reference: string | null, company: string | null, status: string | null, location: string | null, 
/**
 * The Sourcer role already made from this job.
 */
role_id: string | null, };