// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefLines } from "./BriefLines";
import type { RetuneChange } from "./RetuneChange";

/**
 * Claude's reading of a count that found too few people, and the relaxed
 * brief it proposes. Nothing is saved or searched until the resourcer agrees.
 */
export type RetuneView = { 
/**
 * The confirmed brief version this relaxes; confirming checks it.
 */
based_on: number, 
/**
 * Why the search found so few, in plain words.
 */
diagnosis: string, 
/**
 * What changes, line by line.
 */
changes: Array<RetuneChange>, 
/**
 * The whole relaxed brief, ready to confirm.
 */
lines: BriefLines, };
