// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a user may do. Admins also manage the team.
 */
export type Role = "admin" | "resourcer";
