// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Brief } from "./Brief";
import type { Client } from "./Client";
import type { LockedOut } from "./LockedOut";
import type { RecruitlyLink } from "./RecruitlyLink";

export type RoleDetail = { id: string, title: string, client: Client | null, spec_text: string, 
/**
 * The latest version: the open draft if there is one, else the last confirmed.
 */
brief: Brief | null, 
/**
 * Companies whose staff are always left out of this role: the hiring
 * client and every off-limits client. Cannot be removed.
 */
locked_out: Array<LockedOut>, 
/**
 * The Recruitly job this role came from or is linked to.
 */
recruitly_job: RecruitlyLink | null, };
