// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleSummary = { id: string, title: string, client_name: string | null, 
/**
 * "none", "draft" or "confirmed".
 */
brief_state: string, };
