// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleUpdate = { title: string, spec_text: string, 
/**
 * Set the client, only while the role has none. `None` leaves it as it is.
 */
client_id: string | null, };
