// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateRow } from "./CandidateRow";

export type SavedProfile = { 
/**
 * False when the person was already on this role.
 */
added: boolean, candidate: CandidateRow, };
