// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A LinkedIn profile the resourcer is viewing, saved to a role (SRS F10).
 * Filled in from the page when they click the Save button, then checked by them.
 */
export type SaveProfile = { role_id: string, 
/**
 * The profile address, e.g. "https://www.linkedin.com/in/someone/".
 */
linkedin_url: string, name: string, title: string | null, employer: string | null, location: string | null, };
