// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Widen } from "./Widen";

/**
 * PUT /api/roles/:id/searches/:slot
 */
export type SaveSearch = { widen: Widen, };
