// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefLines } from "./BriefLines";
import type { CountView } from "./CountView";
import type { MoreSearch } from "./MoreSearch";
import type { PullView } from "./PullView";

/**
 * The search step for one role, as the Search screen shows it.
 */
export type SearchState = { 
/**
 * The confirmed brief searches use, if there is one.
 */
brief_version: number | null, 
/**
 * The confirmed lines that searches use.
 */
lines: BriefLines | null, 
/**
 * Edits after confirming are not searched until confirmed.
 */
unconfirmed_edits: boolean, 
/**
 * The locations that will each be counted and pulled on their own.
 */
locations: Array<string>, 
/**
 * Why searching is not possible right now, in words for people.
 */
blocked: string | null, count: CountView | null, pull: PullView | null, 
/**
 * A pull for this role, from any search, is still running.
 */
pulling: boolean, 
/**
 * Up to three wider searches of the confirmed brief, by slot.
 */
more: Array<MoreSearch>, 
/**
 * Credits used by this organisation since the start of the month.
 */
credits_this_month: number, };
