// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberStatus } from "./MemberStatus";
import type { Role } from "./Role";

/**
 * One person on the team, as the Team screen shows them.
 */
export type TeamMember = { id: string, name: string, email: string, role: Role, status: MemberStatus, };
