// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TightenKind } from "./TightenKind";

/**
 * One tightening change, with the words of the spec that justify it.
 */
export type TightenMove = { kind: TightenKind, value: string, 
/**
 * Copied from the spec. A change whose quote is not in the spec is dropped.
 */
quote: string, 
/**
 * The change in words, set by the server.
 */
label: string, };
