// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TightenMove } from "./TightenMove";

/**
 * Claude's tightening of a brief that found far too many people. Nothing
 * is saved until the resourcer agrees.
 */
export type TightenView = { 
/**
 * The confirmed brief version this tightens.
 */
based_on: number, 
/**
 * This will be round 1 or 2.
 */
round: number, 
/**
 * Why so many were found, in plain words.
 */
why: string, 
/**
 * People the count found before tightening.
 */
before: number, moves: Array<TightenMove>, };
