// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One way a tightening narrows the brief, towards the spec.
 */
export type TightenKind = "require_tool" | "must_domain" | "drop_title" | "drop_level" | "min_years" | "drop_employer_type" | "set_locations" | "drop_location";
