// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TightenMove } from "./TightenMove";

/**
 * POST /api/roles/:id/search/tighten/apply: the changes the resourcer kept.
 */
export type TightenApply = { based_on: number, moves: Array<TightenMove>, };
