// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodayItem = { candidacy_id: string, role_id: string, role_title: string, name: string, 
/**
 * e.g. "Email 2 due Mon 6 Oct".
 */
note: string, };
