// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodayItem } from "./TodayItem";
import type { TodayReply } from "./TodayReply";

export type TodayView = { replies: Array<TodayReply>, 
/**
 * Your drafted emails, waiting for your approval.
 */
to_approve: Array<TodayItem>, 
/**
 * Your approved emails still to go.
 */
going_out: Array<TodayItem>, 
/**
 * An admin has paused all sending.
 */
paused: boolean, 
/**
 * Your Outlook is connected and working.
 */
outlook_ready: boolean, 
/**
 * Monday to Friday, 08:00 to 18:00 Dubai.
 */
in_hours: boolean, };
