// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodayReply = { candidacy_id: string, role_id: string, role_title: string, name: string, 
/**
 * "reply", "auto" (an automatic reply) or "bounce".
 */
kind: string, 
/**
 * e.g. "2 Oct 2026 09:14" (Dubai).
 */
at: string, 
/**
 * Whose Outlook it came to.
 */
sender: string, 
/**
 * Already on the do-not-contact list or opted out.
 */
opted_out: boolean, };
