// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the client treats a tool named in the spec. Never assumed: the
 * resourcer answers for each tool before a search runs (SRS F4).
 */
export type ToolStatus = "required" | "nice" | "replacing";
