// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a wider search adds to the brief. It can only widen: the search is
 * the brief with these applied, so the people found still fit the job.
 */
export type Widen = { add_titles: Array<string>, add_levels: Array<string>, add_locations: Array<string>, 
/**
 * Only from the employer types Sourcer knows.
 */
add_employer_types: Array<string>, 
/**
 * Required tools, by name, that become nice to have.
 */
tools_to_nice: Array<string>, 
/**
 * Must domains, by name, that become Plus.
 */
domains_to_plus: Array<string>, 
/**
 * Fewer years than the brief asks for; 0 for any. `None` keeps the brief's.
 */
min_years: number | null, };
